services:
  db:
    image: postgres:16
    container_name: sonic_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sonic
      POSTGRES_PASSWORD: sonic123
      POSTGRES_DB: sonic_db
    volumes:
      - sonic_db_data:/var/lib/postgresql/data

volumes:
  sonic_db_data:
